/*
 * CreateDB.java
 *
 * Sukuria HSQLDB 1.8.0.10 embedded duomenu baze, suderinama su LibreOffice Base.
 * Sukuria tris lenteles (Students, Courses, Enrollments) su pirminiais ir
 * isoriniais raktais, ir uzpildo pavyzdiniais duomenimis.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.io.File;

public class CreateDB {
    public static void main(String[] args) throws Exception {
        String outputDir = args.length > 0 ? args[0] : "studentai_db";
        File dir = new File(outputDir + "/database");
        dir.mkdirs();

        String dbPath = new File(outputDir + "/database/db").getAbsolutePath();
        String url = "jdbc:hsqldb:file:" + dbPath + ";shutdown=true";

        Class.forName("org.hsqldb.jdbcDriver");
        Connection conn = DriverManager.getConnection(url, "SA", "");
        Statement st = conn.createStatement();

        System.out.println("Kuriama duomenu baze: " + dbPath);

        st.execute("SET WRITE_DELAY FALSE");

        // HSQLDB 1.8 sintakse - INTEGER IDENTITY (ne GENERATED BY DEFAULT)
        st.execute(
            "CREATE MEMORY TABLE Students (" +
            "  StudentID      INTEGER IDENTITY," +
            "  FirstName      VARCHAR(50) NOT NULL," +
            "  LastName       VARCHAR(50) NOT NULL," +
            "  Email          VARCHAR(100)," +
            "  Major          VARCHAR(50)," +
            "  EnrollmentYear INTEGER," +
            "  CONSTRAINT uq_email UNIQUE (Email)" +
            ")"
        );
        System.out.println("  Sukurta lentele: Students");

        st.execute(
            "CREATE MEMORY TABLE Courses (" +
            "  CourseID    INTEGER IDENTITY," +
            "  CourseName  VARCHAR(100) NOT NULL," +
            "  Credits     INTEGER," +
            "  Department  VARCHAR(50)" +
            ")"
        );
        System.out.println("  Sukurta lentele: Courses");

        st.execute(
            "CREATE MEMORY TABLE Enrollments (" +
            "  EnrollmentID INTEGER IDENTITY," +
            "  StudentID    INTEGER NOT NULL," +
            "  CourseID     INTEGER NOT NULL," +
            "  Semester     VARCHAR(20)," +
            "  Grade        DECIMAL(3,1)," +
            "  FOREIGN KEY (StudentID) REFERENCES Students(StudentID)," +
            "  FOREIGN KEY (CourseID)  REFERENCES Courses(CourseID)" +
            ")"
        );
        System.out.println("  Sukurta lentele: Enrollments");

        st.execute("INSERT INTO Students VALUES(1,'Andrius','Vargonas','andrius.vargonas@knf.vu.lt','Marketingo technologijos',2024)");
        st.execute("INSERT INTO Students VALUES(2,'Egle','Kazlauskaite','egle.k@knf.vu.lt','Verslo informatika',2023)");
        st.execute("INSERT INTO Students VALUES(3,'Tomas','Petrauskas','tomas.p@knf.vu.lt','Marketingo technologijos',2024)");
        st.execute("INSERT INTO Students VALUES(4,'Ruta','Jonaityte','ruta.j@knf.vu.lt','Finansu valdymas',2025)");
        st.execute("INSERT INTO Students VALUES(5,'Mantas','Bagdonas','mantas.b@knf.vu.lt','Verslo informatika',2023)");
        st.execute("INSERT INTO Students VALUES(6,'Lina','Sakalauskaite','lina.s@knf.vu.lt','Marketingo technologijos',2025)");
        System.out.println("  Iterpta 6 irasai i Students");

        st.execute("INSERT INTO Courses VALUES(101,'Skaitmeninio marketingo pagrindai',6,'Marketingo katedra')");
        st.execute("INSERT INTO Courses VALUES(102,'Duomenu bazes ir informacijos sistemos',6,'Informatikos katedra')");
        st.execute("INSERT INTO Courses VALUES(103,'Vartotoju elgsenos analize',5,'Marketingo katedra')");
        st.execute("INSERT INTO Courses VALUES(104,'Verslo statistika',6,'Vadybos katedra')");
        st.execute("INSERT INTO Courses VALUES(105,'Programavimo pagrindai',5,'Informatikos katedra')");
        st.execute("INSERT INTO Courses VALUES(106,'Marketingo strategija',6,'Marketingo katedra')");
        System.out.println("  Iterpta 6 irasai i Courses");

        st.execute("INSERT INTO Enrollments VALUES(1,1,101,'2024 rud.',9.0)");
        st.execute("INSERT INTO Enrollments VALUES(2,1,102,'2024 rud.',8.5)");
        st.execute("INSERT INTO Enrollments VALUES(3,1,103,'2024 pav.',8.0)");
        st.execute("INSERT INTO Enrollments VALUES(4,2,102,'2024 rud.',9.5)");
        st.execute("INSERT INTO Enrollments VALUES(5,2,105,'2024 pav.',9.0)");
        st.execute("INSERT INTO Enrollments VALUES(6,3,101,'2024 rud.',7.5)");
        st.execute("INSERT INTO Enrollments VALUES(7,3,106,'2024 pav.',8.0)");
        System.out.println("  Iterpta 7 irasai i Enrollments");

        st.execute("SHUTDOWN COMPACT");
        st.close();
        conn.close();

        System.out.println("Duomenu baze sukurta: " + dir.getAbsolutePath());

        // Pervadinam failus i LibreOffice Base lauktus pavadinimus
        File scriptOld = new File(outputDir + "/database/db.script");
        File scriptNew = new File(outputDir + "/database/script");
        if (scriptOld.exists()) {
            scriptOld.renameTo(scriptNew);
            System.out.println("  Pervadinta: db.script -> script");
        }
        File propOld = new File(outputDir + "/database/db.properties");
        File propNew = new File(outputDir + "/database/properties");
        if (propOld.exists()) {
            propOld.renameTo(propNew);
            System.out.println("  Pervadinta: db.properties -> properties");
        }
        new File(outputDir + "/database/db.lck").delete();
        new File(outputDir + "/database/db.log").delete();
        new File(outputDir + "/database/db.data").delete();
        new File(outputDir + "/database/db.backup").delete();

        File[] files = dir.listFiles();
        if (files != null) {
            System.out.println("Failai:");
            for (File f : files) {
                System.out.println("  " + f.getName() + " (" + f.length() + " B)");
            }
        }
    }
}
